using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class SoundMetadata {

    public static Dictionary<SoundType, Dictionary<UnitType, int>> VoiceCountsDictionary = new Dictionary<SoundType, Dictionary<UnitType, int>> {
        {SoundType.Ability, new Dictionary<UnitType, int> {
            {UnitType.heavy_albarn, 2 },
            {UnitType.piercing_tungsten, 3 },
            {UnitType.light_adren, 6 },
            {UnitType.support_sandman, 3 },
        } },
        {SoundType.Annoyed, new Dictionary<UnitType, int> {
            {UnitType.trooper, 9 },
            {UnitType.recon, 5 },
            {UnitType.steamer, 9 },
            {UnitType.pewpew, 4 },
            {UnitType.compensator, 10 },
            {UnitType.foundation, 4 },
            {UnitType.powerSurge, 4 },
            {UnitType.midas, 12 },
            {UnitType.claymore, 3 },
            {UnitType.heavy_albarn, 7 },
            {UnitType.piercing_tungsten, 8 },
            {UnitType.light_adren, 6 },
            {UnitType.support_sandman, 5 },
        } },
        {SoundType.Attack, new Dictionary<UnitType, int> {
            {UnitType.trooper, 10 },
            {UnitType.recon, 15 },
            {UnitType.steamer, 10 },
            {UnitType.pewpew, 8 },
            {UnitType.compensator, 17 },
            {UnitType.foundation, 4 },
            {UnitType.powerSurge, 10 },
            {UnitType.midas, 13 },
            {UnitType.claymore, 10 },
            {UnitType.heavy_albarn, 4 },
            {UnitType.piercing_tungsten, 1 },
            {UnitType.light_adren, 4 },
            {UnitType.support_sandman, 5 },
        } },
        {SoundType.Death, new Dictionary<UnitType, int> {
            {UnitType.trooper, 5 },
            {UnitType.recon, 4 },
            {UnitType.steamer, 6 },
            {UnitType.pewpew, 4 },
            {UnitType.compensator, 3 },
            {UnitType.foundation, 2 },
            {UnitType.powerSurge, 5 },
            {UnitType.midas, 4 },
            {UnitType.claymore, 6 },
            {UnitType.heavy_albarn, 5 },
            {UnitType.piercing_tungsten, 0 },
            {UnitType.light_adren, 4 },
            {UnitType.support_sandman, 2 },
        } },
        {SoundType.Move, new Dictionary<UnitType, int> {
            {UnitType.trooper, 4 },
            {UnitType.recon, 9 },
            {UnitType.steamer, 4 },
            {UnitType.pewpew, 7 },
            {UnitType.compensator, 2 },
            {UnitType.foundation, 6 },
            {UnitType.powerSurge, 7 },
            {UnitType.midas, 7 },
            {UnitType.claymore, 9 },
            {UnitType.heavy_albarn, 0 },
            {UnitType.piercing_tungsten, 5 },
            {UnitType.light_adren, 5 },
            {UnitType.support_sandman, 7 },
        } },
        {SoundType.Select, new Dictionary<UnitType, int> {
            {UnitType.trooper, 6 },
            {UnitType.recon, 3 },
            {UnitType.steamer, 5 },
            {UnitType.pewpew, 4 },
            {UnitType.compensator, 5 },
            {UnitType.foundation, 2 },
            {UnitType.powerSurge, 7 },
            {UnitType.midas, 5 },
            {UnitType.claymore, 6 },
            {UnitType.heavy_albarn, 6 },
            {UnitType.piercing_tungsten, 5 },
            {UnitType.light_adren, 4 },
            {UnitType.support_sandman, 7 },
        } },
        {SoundType.TakeDamage, new Dictionary<UnitType, int> {
            {UnitType.trooper, 1 },
            {UnitType.recon, 3 },
            {UnitType.steamer, 1 },
            {UnitType.pewpew, 1 },
            {UnitType.compensator, 4 },
            {UnitType.foundation, 3 },
            {UnitType.powerSurge, 2 },
            {UnitType.midas, 3 },
            {UnitType.claymore, 2 },
            {UnitType.heavy_albarn, 2 },
            {UnitType.piercing_tungsten, 2 },
            {UnitType.light_adren, 1 },
            {UnitType.support_sandman, 3 },
        } },
    };
}
