using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class SoundMetadata {

    public static Dictionary<SoundType, Dictionary<UnitType, int>> VoiceCountsDictionary = new Dictionary<SoundType, Dictionary<UnitType, int>> {
        {SoundType.Ability, new Dictionary<UnitType, int> {
            {UnitType.heavy_albarn, 2 },
            {UnitType.piercing_tungsten, 0 },
            {UnitType.light_adren, 6 },
            {UnitType.support_sandman, 0 },
        } },
        {SoundType.Annoyed, new Dictionary<UnitType, int> {
            {UnitType.trooper, 0 },
            {UnitType.recon, 0 },
            {UnitType.steamer, 0 },
            {UnitType.pewpew, 0 },
            {UnitType.compensator, 10 },
            {UnitType.foundation, 4 },
            {UnitType.powerSurge, 0 },
            {UnitType.midas, 0 },
            {UnitType.claymore, 3 },
            {UnitType.heavy_albarn, 7 },
            {UnitType.piercing_tungsten, 0 },
            {UnitType.light_adren, 6 },
            {UnitType.support_sandman, 0 },
        } },
        {SoundType.Attack, new Dictionary<UnitType, int> {
            {UnitType.trooper, 0 },
            {UnitType.recon, 0 },
            {UnitType.steamer, 0 },
            {UnitType.pewpew, 4 },
            {UnitType.compensator, 17 },
            {UnitType.foundation, 0 },
            {UnitType.powerSurge, 0 },
            {UnitType.midas, 0 },
            {UnitType.claymore, 10 },
            {UnitType.heavy_albarn, 4 },
            {UnitType.piercing_tungsten, 0 },
            {UnitType.light_adren, 4 },
            {UnitType.support_sandman, 0 },
        } },
        {SoundType.Death, new Dictionary<UnitType, int> {
            {UnitType.trooper, 0 },
            {UnitType.recon, 0 },
            {UnitType.steamer, 0 },
            {UnitType.pewpew, 0 },
            {UnitType.compensator, 3 },
            {UnitType.foundation, 2 },
            {UnitType.powerSurge, 0 },
            {UnitType.midas, 0 },
            {UnitType.claymore, 6 },
            {UnitType.heavy_albarn, 5 },
            {UnitType.piercing_tungsten, 0 },
            {UnitType.light_adren, 4 },
            {UnitType.support_sandman, 0 },
        } },
        {SoundType.Move, new Dictionary<UnitType, int> {
            {UnitType.trooper, 0 },
            {UnitType.recon, 0 },
            {UnitType.steamer, 0 },
            {UnitType.pewpew, 0 },
            {UnitType.compensator, 2 },
            {UnitType.foundation, 6 },
            {UnitType.powerSurge, 0 },
            {UnitType.midas, 0 },
            {UnitType.claymore, 9 },
            {UnitType.heavy_albarn, 0 },
            {UnitType.piercing_tungsten, 0 },
            {UnitType.light_adren, 5 },
            {UnitType.support_sandman, 0 },
        } },
        {SoundType.Select, new Dictionary<UnitType, int> {
            {UnitType.trooper, 0 },
            {UnitType.recon, 0 },
            {UnitType.steamer, 0 },
            {UnitType.pewpew, 0 },
            {UnitType.compensator, 5 },
            {UnitType.foundation, 2 },
            {UnitType.powerSurge, 0 },
            {UnitType.midas, 0 },
            {UnitType.claymore, 6 },
            {UnitType.heavy_albarn, 6 },
            {UnitType.piercing_tungsten, 0 },
            {UnitType.light_adren, 4 },
            {UnitType.support_sandman, 0 },
        } },
        {SoundType.TakeDamage, new Dictionary<UnitType, int> {
            {UnitType.trooper, 0 },
            {UnitType.recon, 0 },
            {UnitType.steamer, 0 },
            {UnitType.pewpew, 0 },
            {UnitType.compensator, 4 },
            {UnitType.foundation, 3 },
            {UnitType.powerSurge, 0 },
            {UnitType.midas, 0 },
            {UnitType.claymore, 2 },
            {UnitType.heavy_albarn, 2 },
            {UnitType.piercing_tungsten, 0 },
            {UnitType.light_adren, 1 },
            {UnitType.support_sandman, 0 },
        } },
    };
}
